import { Work_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const worksans = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${worksans.className} flex justify-center items-center flex-col`}
      >
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
